"""Gave gin to models

Revision ID: b3aca7fa8068
Revises: 4475064c1feb
Create Date: 2025-12-11 17:15:53.203209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3aca7fa8068'
down_revision: Union[str, Sequence[str], None] = '4475064c1feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', name || ' ' || coalesce(description, ''))", persisted=True), nullable=False))
    op.create_index('idx_item_search_vector', 'items', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_item_search_vector', table_name='items', postgresql_using='gin')
    op.drop_column('items', 'search_vector')
    # ### end Alembic commands ###
